---
name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install deps & build"
        run: ./scripts/build.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Orienteering times"
          prerelease: false
          files: ./server/bin/orienteering-times*
